### ISSUE TITLE
Can it be integrated into the SD webui?

### ISSUE THREAD

**Issue by ZZfive** [openai/consistencydecoder#6]
Is the decoding performance of "consistencydecoder" better than that in "sd webui"? Can it be integrated for use within "sd webui"?

**Comment by fgtm2023** [comment]
I'm waiting for this too 🤞🤞🤞🤞

**Comment by KohakuBlueleaf** [comment]
@ZZfive @fgtm2023 Please check the consistency-dec branch in sd-webui
it is planed to be built-in feature

**Comment by ZZfive** [comment]
> @ZZfive @fgtm2023 Please check the consistency-dec branch in sd-webui it is planed to be built-in feature

thanks for your good job

**Comment by shitianfang** [comment]
@KohakuBlueleaf How do I use webui when it is not updated?
